language: php

php:
  - 5.6

install:
  - composer install --prefer-dist --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - burgess.chen.104@gmail.com
    on_success: always
    on_failure: always

script: vendor/bin/phpunit -c phpunit.xml --coverage-text